dist: xenial

language: rust

services:
  - docker

before_install:
  - docker -v
  - ./build.sh
  - docker images

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zboxfs/base

notifications:
  email:
    on_success: never
